"""empty message

Revision ID: 508b6cee4a69
Revises: d7f81d8b31d3
Create Date: 2023-06-29 13:45:38.249285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508b6cee4a69'
down_revision = 'd7f81d8b31d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password2', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password2')

    # ### end Alembic commands ###
