"""empty message

Revision ID: 88515592df00
Revises: a7e3424e6256
Create Date: 2023-07-28 10:48:03.475461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88515592df00'
down_revision = 'a7e3424e6256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('date_edited',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_edited',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date_edited',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('date_edited',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
